version: '3.4'
services:
  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/code
    working_dir: /code/familyfeud
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 && django-admin collectstatic"
    tty: true
  redis:
    image: redis:alpine