version: '3.4'
services:
  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/code
    working_dir: /code/familyfeud
    command: python manage.py runserver 0.0.0.0:8000
    tty: true
  redis:
    image: redis:alpine