# Generated by Django 2.2.2 on 2019-06-25 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190624_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1_score', models.IntegerField(default=0)),
                ('team_2_score', models.IntegerField(default=0)),
                ('question_total', models.IntegerField(default=0)),
                ('question_total_wrong', models.IntegerField(default=0)),
                ('current_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Game')),
                ('current_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Question')),
            ],
        ),
    ]
