# Generated by Django 2.2.2 on 2019-06-25 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_gamestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestatus',
            name='current_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Game'),
        ),
        migrations.AlterField(
            model_name='gamestatus',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Question'),
        ),
    ]
