# Generated by Django 2.2.2 on 2019-06-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_gamestatus_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_order',
            field=models.IntegerField(default=0),
        ),
    ]
