# Generated by Django 2.2.2 on 2019-06-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_question_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='displayed_answers',
            field=models.CharField(default='{"displayed":[]}', max_length=1000),
        ),
    ]
