# Generated by Django 2.2.2 on 2019-06-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_gamestatus_displayed_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='displayLogo',
            field=models.BooleanField(default=True),
        ),
    ]
