# Generated by Django 2.2.2 on 2019-06-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_gamestatus_displaylogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestatus',
            old_name='displayLogo',
            new_name='display_logo',
        ),
    ]
