# Generated by Django 2.2.2 on 2019-06-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20190627_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='new_displayed_answers',
            field=models.ManyToManyField(to='base.Answer'),
        ),
    ]
