# Generated by Django 2.2.2 on 2019-07-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_gamestatus_new_displayed_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestatus',
            name='new_displayed_answers',
        ),
        migrations.RemoveField(
            model_name='gamestatus',
            name='displayed_answers',
        ),
        migrations.AddField(
            model_name='gamestatus',
            name='displayed_answers',
            field=models.ManyToManyField(to='base.Answer'),
        ),
    ]
