# Generated by Django 2.2.2 on 2019-07-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20190701_1442'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='QuestionSet',
        ),
    ]

    atomic = False
