# Generated by Django 2.2.2 on 2019-07-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20190701_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_fast_money',
            field=models.BooleanField(default=False),
        ),
    ]
