# Generated by Django 2.2.2 on 2019-07-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20190705_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='start_timer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamestatus',
            name='timer',
            field=models.IntegerField(default=20),
        ),
    ]
