# Generated by Django 2.2.2 on 2019-07-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20190705_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='is_fast_money',
            field=models.BooleanField(default=False),
        ),
    ]
