# Generated by Django 2.2.2 on 2019-07-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_gamestatus_is_fast_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fastmoneyanswer',
            old_name='question_id',
            new_name='question',
        ),
    ]
