# Generated by Django 2.2.2 on 2019-07-09 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20190705_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='last_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_question', to='base.Question'),
        ),
    ]
