# Generated by Django 2.2.2 on 2019-07-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_gamestatus_last_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestatus',
            name='start_timer',
        ),
    ]
