# Generated by Django 2.2.2 on 2019-07-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_gamestatus_start_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastmoneyanswer',
            name='answer_id',
            field=models.IntegerField(default=0),
        ),
    ]
