# Generated by Django 2.2.2 on 2019-07-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_fastmoneyanswer_answer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='display_timer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamestatus',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
