# Generated by Django 2.2.2 on 2019-07-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20190712_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='team_1_name',
            field=models.CharField(default='Team 1', max_length=500),
        ),
        migrations.AddField(
            model_name='gamestatus',
            name='team_2_name',
            field=models.CharField(default='Team 2', max_length=500),
        ),
    ]
