# Generated by Django 2.2.3 on 2019-07-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20190719_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='display_winner_screen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamestatus',
            name='winner_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
