# Generated by Django 2.2.3 on 2019-08-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20190731_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score_multiplier',
            field=models.IntegerField(default=1),
        ),
    ]
