# Generated by Django 2.2.4 on 2019-08-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_question_score_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestatus',
            name='timer',
            field=models.IntegerField(default=25),
        ),
    ]
