# Generated by Django 2.2.4 on 2019-08-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20190812_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestatus',
            name='team_1_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='gamestatus',
            name='team_2_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
