# Generated by Django 2.2.4 on 2019-08-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20190814_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='cooperative_fm',
            field=models.BooleanField(default=True),
        ),
    ]
