# Generated by Django 2.2.4 on 2019-08-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_gamestatus_current_fm_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='display_picture',
            field=models.BooleanField(default=False),
        ),
    ]
